// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.Ultrasonic;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput sensorSubsystemlineIRSensorSwitch;
    public static Ultrasonic sensorSubsystemrangeFinder;
    public static DigitalInput sensorSubsystemcollisionIRSensorSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        sensorSubsystemlineIRSensorSwitch = new DigitalInput(6);
        LiveWindow.addSensor("sensorSubsystem", "lineIRSensorSwitch", sensorSubsystemlineIRSensorSwitch);
        
        sensorSubsystemrangeFinder = new Ultrasonic(9, 8);
        LiveWindow.addSensor("sensorSubsystem", "rangeFinder", sensorSubsystemrangeFinder);
        
        sensorSubsystemcollisionIRSensorSwitch = new DigitalInput(7);
        LiveWindow.addSensor("sensorSubsystem", "collisionIRSensorSwitch", sensorSubsystemcollisionIRSensorSwitch);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
